import { createElement } from "react";
import {
  // General
  List,
  Star,
  Heart,
  Bookmark,
  Flag,
  Folder,
  Archive,
  Inbox,
  Layers,
  Target,
  CircleCheck,
  Pin,
  Tag,
  Zap,
  Flame,
  Shield,
  Crown,
  Gem,
  Eye,
  Bell,
  // Home & lifestyle
  Home,
  Bed,
  Sofa,
  Bath,
  Lamp,
  Key,
  Lock,
  // Work & productivity
  Briefcase,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Clock,
  Calendar,
  CalendarDays,
  Lightbulb,
  PenLine,
  FileText,
  ClipboardList,
  // Communication
  Mail,
  MessageCircle,
  Phone,
  Send,
  Users,
  UserPlus,
  // Shopping & finance
  ShoppingBag,
  ShoppingCart,
  Wallet,
  CreditCard,
  DollarSign,
  Receipt,
  Gift,
  Percent,
  // Food & drink
  Coffee,
  Utensils,
  Wine,
  Apple,
  CookingPot,
  IceCreamCone,
  Cake,
  // Travel & transport
  Car,
  Plane,
  Train,
  Bike,
  Ship,
  MapPin,
  Map,
  Compass,
  Navigation,
  Globe,
  // Education & learning
  GraduationCap,
  Book,
  BookOpen,
  Library,
  Pencil,
  School,
  // Health & fitness
  Dumbbell,
  HeartPulse,
  Pill,
  Stethoscope,
  Activity,
  Baby,
  Syringe,
  // Entertainment & media
  Music,
  Camera,
  Film,
  Tv,
  Gamepad2,
  Headphones,
  Mic,
  Radio,
  Palette,
  // Nature & weather
  Sun,
  Moon,
  CloudSun,
  Snowflake,
  TreePine,
  Flower2,
  Leaf,
  Mountain,
  Waves,
  // Tools & building
  Wrench,
  Hammer,
  Scissors,
  Ruler,
  Cog,
  CircuitBoard,
  // Sports & outdoors
  Trophy,
  Medal,
  Tent,
  FishSymbol,
  // Animals
  Dog,
  Cat,
  Bird,
  Fish,
  Bug,
  Squirrel,
  Rabbit,
  type LucideIcon,
} from "lucide-react";

export const LIST_ICONS: Record<string, LucideIcon> = {
  // General
  list: List,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  flag: Flag,
  folder: Folder,
  archive: Archive,
  inbox: Inbox,
  layers: Layers,
  target: Target,
  "circle-check": CircleCheck,
  pin: Pin,
  tag: Tag,
  zap: Zap,
  flame: Flame,
  shield: Shield,
  crown: Crown,
  gem: Gem,
  eye: Eye,
  bell: Bell,
  // Home & lifestyle
  home: Home,
  bed: Bed,
  sofa: Sofa,
  bath: Bath,
  lamp: Lamp,
  key: Key,
  lock: Lock,
  // Work & productivity
  briefcase: Briefcase,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  clock: Clock,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  lightbulb: Lightbulb,
  "pen-line": PenLine,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  // Communication
  mail: Mail,
  "message-circle": MessageCircle,
  phone: Phone,
  send: Send,
  users: Users,
  "user-plus": UserPlus,
  // Shopping & finance
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  wallet: Wallet,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  receipt: Receipt,
  gift: Gift,
  percent: Percent,
  // Food & drink
  coffee: Coffee,
  utensils: Utensils,
  wine: Wine,
  apple: Apple,
  "cooking-pot": CookingPot,
  "ice-cream-cone": IceCreamCone,
  cake: Cake,
  // Travel & transport
  car: Car,
  plane: Plane,
  train: Train,
  bike: Bike,
  ship: Ship,
  "map-pin": MapPin,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  globe: Globe,
  // Education & learning
  "graduation-cap": GraduationCap,
  book: Book,
  "book-open": BookOpen,
  library: Library,
  pencil: Pencil,
  school: School,
  // Health & fitness
  dumbbell: Dumbbell,
  "heart-pulse": HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  activity: Activity,
  baby: Baby,
  syringe: Syringe,
  // Entertainment & media
  music: Music,
  camera: Camera,
  film: Film,
  tv: Tv,
  gamepad2: Gamepad2,
  headphones: Headphones,
  mic: Mic,
  radio: Radio,
  palette: Palette,
  // Nature & weather
  sun: Sun,
  moon: Moon,
  "cloud-sun": CloudSun,
  snowflake: Snowflake,
  "tree-pine": TreePine,
  flower2: Flower2,
  leaf: Leaf,
  mountain: Mountain,
  waves: Waves,
  // Tools & building
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  ruler: Ruler,
  cog: Cog,
  "circuit-board": CircuitBoard,
  // Sports & outdoors
  trophy: Trophy,
  medal: Medal,
  tent: Tent,
  "fish-symbol": FishSymbol,
  // Animals
  dog: Dog,
  cat: Cat,
  bird: Bird,
  fish: Fish,
  bug: Bug,
  squirrel: Squirrel,
  rabbit: Rabbit,
};

export function getListIcon(iconName: string | null): LucideIcon {
  if (iconName && LIST_ICONS[iconName]) {
    return LIST_ICONS[iconName];
  }
  return List;
}

export function ListIcon({ icon, className }: { icon: string | null; className?: string }) {
  return createElement(getListIcon(icon), { className });
}
